### ISSUE TITLE
Py3 compatibility commits not released in Pypi

### ISSUE THREAD

**Issue by vokimon** [gisce/xmlrpclib-to#3]
The last version of this package was published to PyPi on 4th Dec 2014. It does not contain the latest commits pushed some days later, which includes some interesting Python3 compatibility fixes (regarding httplib).

It would be nice to have those fixes in the pypi version so we can run our code in Py3.

Thanks.

**Comment by ecarreras** [comment]
Released a new version v0.1.2 and upload to pypi: https://pypi.org/project/xmlrpclib-to/0.1.2/

**Comment by vokimon** [comment]
Cool! thanks!
